/*     
 *    
 *  Author     : ACIMS(Arizona Centre for Integrative Modeling & Simulation)
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 08-15-02 
 */
package Component.Jessi;

import java.awt.*;

import GenCol.*;


import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;



public class gpt extends ViewableDigraph{


public gpt(){
    super("gpt");

    ViewableAtomic g = new genr("generator",1);
    ViewableAtomic p = new proc("attraction1",10);
    ViewableAtomic p2 = new proc("attraction2",5);
    ViewableAtomic p3 = new proc("attraction3",7);
    ViewableAtomic t1 = new transd("transducer1",370,10);
    ViewableAtomic t2 = new transd("transducer2",370,5);
    ViewableAtomic t3 = new transd("transducer3",370,20);
//    ViewableAtomic t2 = new transd("transducer",370);
//    ViewableAtomic t3 = new transd("transducer",370);
    ViewableAtomic m = new monitor("monitor",10);

     add(g);
     add(p);
     add(p2);
     add(p3);
     add(m);
//     add(t);
     add(t1);
     add(t2);
     add(t3);

    addInport("in");
    addInport("start");
    addInport("stop");
    addInport("stop1");
    addOutport("FastPass");
    addOutport("Normal");

     addTestInput("start",new entity());
     addTestInput("stop1",new visitor());

     addCoupling(this,"in",g,"in");
//
     addCoupling(this,"start",g,"start");
     addCoupling(this,"stop",g,"stop");

    addCoupling(g,"out",p,"in");
    addCoupling(g,"out",p2,"in");
    addCoupling(g,"out",p3,"in");
//
     addCoupling(g,"out",t1,"ariv");
     addCoupling(p,"out",t1,"solved");
     addCoupling(p2,"out",t1,"other");
     addCoupling(p3,"out",t1,"other");
     
     addCoupling(g,"out",t2,"ariv");
     addCoupling(p2,"out",t2,"solved");
     addCoupling(p,"out",t2,"other");
     addCoupling(p3,"out",t2,"other");
     
     addCoupling(g,"out",t3,"ariv");
     addCoupling(p3,"out",t3,"solved");
     addCoupling(p2,"out",t3,"other");
     addCoupling(p,"out",t3,"other");
     
     //addCoupling(p,"out",t1,"solved");


     addCoupling(t1,"waitingTime",m,"waitingTime");
     addCoupling(t1,"T",p,"in");
     addCoupling(t1,"T",p2,"in");
     addCoupling(t1,"T",p3,"in");
     
     addCoupling(t2,"waitingTime",m,"waitingTime");
     addCoupling(t2,"T",p,"in");
     addCoupling(t2,"T",p2,"in");
     addCoupling(t2,"T",p3,"in");
     
     addCoupling(t3,"waitingTime",m,"waitingTime");
     addCoupling(t3,"T",p,"in");
     addCoupling(t3,"T",p2,"in");
     addCoupling(t3,"T",p3,"in");
     
     //addCoupling(t,"finish",p,"finish");
     addCoupling(m,"FastPass",this,"FastPass");
     addCoupling(m,"Normal",this,"Normal");
     addCoupling(this,"stop1",m,"stop");



 //    initialize();
    // showState();
/*
    preferredSize = new Dimension(484, 145);
    g.setPreferredLocation(new Point(13, 18));
    p.setPreferredLocation(new Point(195, 18));
    t.setPreferredLocation(new Point(193, 80));
    */
}


    
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(750, 346);
        ((ViewableComponent)withName("generator")).setPreferredLocation(new Point(-38, 101));
        ((ViewableComponent)withName("transducer3")).setPreferredLocation(new Point(271, 216));
        ((ViewableComponent)withName("monitor")).setPreferredLocation(new Point(435, 83));
        ((ViewableComponent)withName("attraction3")).setPreferredLocation(new Point(126, 219));
        ((ViewableComponent)withName("attraction2")).setPreferredLocation(new Point(120, 135));
        ((ViewableComponent)withName("attraction1")).setPreferredLocation(new Point(117, 53));
        ((ViewableComponent)withName("transducer2")).setPreferredLocation(new Point(264, 138));
        ((ViewableComponent)withName("transducer1")).setPreferredLocation(new Point(262, 57));
    }
}
